### ISSUE TITLE
No replicas scenario

### ISSUE THREAD

**Issue by bwstaple** [mehrdadjg/Scalability-Dolphins#13]
If there are no replicas ignore incoming updates and send error messages.

**Comment by AhmedAlK** [comment]
The documentation specifies a generic error message of - “error” <newline>
perhaps a more specific error would work better such as - “error: system offline” <newline>

**Comment by AhmedAlK** [comment]
The code has been added but disabled in the proxy recovery branch while waiting on #24

**Comment by AhmedAlK** [comment]
Implemented in #37
