### ISSUE TITLE
handling of incorrect protocol formats

### ISSUE THREAD

**Issue by AhmedAlK** [mehrdadjg/Scalability-Dolphins#24]
Incoming messages should be checked to ensure they follow protocol before being used in operations. This increases reliability and prevents one node's failure from collapsing other nodes in the network if the failing node sends junk.

**Comment by mehrdadjg** [comment]
I'll do this.

**Comment by mehrdadjg** [comment]
Sorry I closed it by mistake.

**Comment by bwstaple** [comment]
update the bundle as well man.
