### ISSUE TITLE
Refactor of proxyWorkers

### ISSUE THREAD

**Issue by bwstaple** [mehrdadjg/Scalability-Dolphins#27]
Dear diary,
There are rare bugs that occur due to concurrent access of proxyWorker resources. This can be mitigated by the use of synchronized methods to access these resources. In addition, using a group manager will increase thread safety when dealing with multiple threaded proxyWorkers that may be deleted by any thread.

**Comment by AhmedAlK** [comment]
the underlying issue has been fixed in #31 without implementing a group manager

**Comment by AhmedAlK** [comment]
fixed again with #37
