### ISSUE TITLE
Make error messaging consistant across Client and Replica

### ISSUE THREAD

**Issue by bwstaple** [mehrdadjg/Scalability-Dolphins#34]
Yeah... that....

**Comment by AhmedAlK** [comment]
Could you clarify? Do you mean to use similar styles with regards to the console output?
eg.
Replica repeats: "Disconnected from proxy. attempting reconnect"
Client uses color coded announcements "Reconnect failed" and "attempting to reconnect..."

**Comment by bwstaple** [comment]
The messages printed by the clients and replicas are really different. It's not a high priority.
