### ISSUE TITLE
document updates and code comments

### ISSUE THREAD

**Issue by mehrdadjg** [mehrdadjg/Scalability-Dolphins#35]

**Comment by AhmedAlK** [comment]
I have added section 3.2 "Client synchronization" to the document.

**Comment by AhmedAlK** [comment]
Section 4 "Data Management" has been added to the document.

**Comment by AhmedAlK** [comment]
The following topics are currently missing from the design document:
-types of failures that are recoverable
-a link to the code repository
-scalability and the use of multiple proxies
-Partial replication such that each replica contains a different subset of all available documents

**Comment by AhmedAlK** [comment]
split off into #52 #53 #54
